pull_request_rules:
  - name: Automatic merge when CI passes
    conditions:
      - check-success=test (30.2, 3.11)
      - -conflict
      - -draft
      # Filters out PRs with "wip" (case insensitive) in the title
      - -title~= (?i)wip
    actions:
      merge:
        method: merge
      delete_head_branch: {}

  - name: Dispatch GitHub Actions
    conditions:
      - label = dispatch
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: ci.yml
